/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import Controller.FuncionarioController;
import Controller.ClienteController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author a1600052
 */
public class CadFuncionarioCliente extends javax.swing.JFrame {

    /**
     * Creates new form CFuncionario
     */
    public CadFuncionarioCliente() {
        initComponents();
    }
    int admin = 0;

    String matricula, cargo, nome, telefone, senha;
    int idade;
    float salario;
    private List<Funcionario> clienteList = new FuncionarioController().listaFuncionarios();
 private int registroAtual = 0;
	private Long key;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AbaFuncionario = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BotaoGravarC = new javax.swing.JButton();
        BotaoVoltarC = new javax.swing.JButton();
        CampoNomeC = new javax.swing.JTextField();
        CampoEndereço = new javax.swing.JTextField();
        CampoTelefoneC = new javax.swing.JTextField();
        CampoCod = new javax.swing.JTextField();
        BotaoLimparC = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BotaoVoltarF = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CampoMatriculaF = new javax.swing.JTextField();
        CampoCargoF = new javax.swing.JTextField();
        CampoNomeF = new javax.swing.JTextField();
        CampoIdadeF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CampoSalarioF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CampoTelefoneF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CampoSenhaF = new javax.swing.JTextField();
        BotaoSalvarF = new javax.swing.JButton();
        BotaoLimparF = new javax.swing.JButton();
        CheckAdmin = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NOME:");

        jLabel2.setText("Código do Cliente:");

        jLabel3.setText("E-MAIL:");

        jLabel4.setText("TELEFONE:");

        BotaoGravarC.setText("GRAVAR");
        BotaoGravarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGravarCActionPerformed(evt);
            }
        });

        BotaoVoltarC.setText("VOLTAR");
        BotaoVoltarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarCActionPerformed(evt);
            }
        });

        BotaoLimparC.setText("LIMPAR CAMPOS");
        BotaoLimparC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoCod, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CampoTelefoneC, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                    .addComponent(CampoEndereço)
                                    .addComponent(CampoNomeC))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotaoVoltarC)
                        .addGap(18, 18, 18))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotaoGravarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoLimparC, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addGap(0, 155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoVoltarC)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CampoCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CampoNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CampoEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CampoTelefoneC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotaoGravarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(BotaoLimparC))
        );

        AbaFuncionario.addTab("Cliente ", jPanel1);

        BotaoVoltarF.setText("VOLTAR");
        BotaoVoltarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarFActionPerformed(evt);
            }
        });

        jLabel5.setText("MATRICULA:");

        jLabel6.setText("NOME:");

        jLabel7.setText("IDADE:");

        jLabel8.setText("CARGO:");

        CampoMatriculaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoMatriculaFActionPerformed(evt);
            }
        });

        CampoNomeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeFActionPerformed(evt);
            }
        });

        CampoIdadeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoIdadeFActionPerformed(evt);
            }
        });

        jLabel9.setText("ANOS");

        jLabel10.setText("SALARIO: R$");

        CampoSalarioF.setText("0.00");

        jLabel11.setText("TELEFONE:");

        jLabel13.setText("SENHA:");

        BotaoSalvarF.setText("GRAVAR");
        BotaoSalvarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarFActionPerformed(evt);
            }
        });

        BotaoLimparF.setText("LIMPAR CAMPOS");
        BotaoLimparF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparFActionPerformed(evt);
            }
        });

        CheckAdmin.setText("Colocar no grupo de Admin");
        CheckAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoNomeF))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoMatriculaF, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoCargoF)))
                        .addGap(18, 18, 18)
                        .addComponent(BotaoVoltarF))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotaoLimparF, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(65, 65, 65)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(BotaoSalvarF)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CampoTelefoneF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel13)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CampoSenhaF, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CampoIdadeF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CampoSalarioF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(CheckAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8)
                        .addComponent(CampoMatriculaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CampoCargoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotaoVoltarF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CampoNomeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CampoIdadeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(CampoSalarioF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CampoTelefoneF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(CampoSenhaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CheckAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(BotaoSalvarF)
                .addGap(18, 18, 18)
                .addComponent(BotaoLimparF)
                .addContainerGap())
        );

        AbaFuncionario.addTab("Funcionário", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AbaFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AbaFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoGravarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGravarCActionPerformed
 String Cod,NomeC,Email,TelefoneC;
       Cod=CampoCod.getText();
       NomeC=CampoNomeC.getText();
       Email=CampoEndereço.getText();
       TelefoneC=CampoTelefoneC.getText();
    
       try{
           new ClienteController().salvar(Cod,NomeC,Email,TelefoneC);
           JOptionPane.showMessageDialog(null,"Cliente Cadastrado com Sucesso!!!");
       }catch(SQLException | ParseException ex){
          Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }       
       clearFieldsC();
    }//GEN-LAST:event_BotaoGravarCActionPerformed

    private void BotaoVoltarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarCActionPerformed
new EntradaAdmin().setVisible(true);
setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_BotaoVoltarCActionPerformed

    private void BotaoVoltarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarFActionPerformed
new EntradaAdmin().setVisible(true);
setVisible(false);
    }//GEN-LAST:event_BotaoVoltarFActionPerformed

    private void CampoNomeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeFActionPerformed

    private void CampoIdadeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoIdadeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoIdadeFActionPerformed

    private void CheckAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAdminActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_CheckAdminActionPerformed

    private void BotaoSalvarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarFActionPerformed
        if (CheckAdmin.isSelected()) {
            admin = 1;
        } else {
            admin = 0;
        }
        System.out.println(admin);// TODO add your handling code here:
        matricula = CampoMatriculaF.getText();
        nome = CampoNomeF.getText();
        cargo = CampoCargoF.getText();
        telefone = CampoTelefoneF.getText();
        senha = CampoSenhaF.getText();
        idade = Integer.parseInt(CampoIdadeF.getText());
        salario = Float.parseFloat(CampoSalarioF.getText());
        Funcionario f=new Funcionario();
        f.setAdmin(admin);
        
        try{
                       
            new FuncionarioController().salvar(matricula, nome, idade, cargo, salario, telefone, senha, f.getAdmin());
          JOptionPane.showMessageDialog(null,"Funcionário cadastrado com sucesso!!!");
                   
//new FuncionarioController().listaFuncionarios();
        }catch(SQLException | ParseException ex) {
          // JOptionPane.showMessageDialog(null,"Já existe um funcionário cadastrado com a mesma matricula");
           Logger.getLogger(Funcionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearFieldsF();
    }//GEN-LAST:event_BotaoSalvarFActionPerformed

    private void CampoMatriculaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoMatriculaFActionPerformed
      
           
       
    }//GEN-LAST:event_CampoMatriculaFActionPerformed

    private void BotaoLimparCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparCActionPerformed
clearFieldsC();        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoLimparCActionPerformed

    private void BotaoLimparFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparFActionPerformed
clearFieldsF();        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoLimparFActionPerformed
public void clearFieldsC(){
    CampoCod.setText("");
    CampoNomeC.setText("");
    CampoEndereço.setText("");
    CampoTelefoneC.setText("");
    
}
public void clearFieldsF(){
    CampoMatriculaF.setText("");
    CampoNomeF.setText("");
    CampoIdadeF.setText("");
    CampoCargoF.setText("");
    CampoSalarioF.setText("");
    CampoTelefoneF.setText("");
    CampoSenhaF.setText("");
    
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadFuncionarioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AbaFuncionario;
    private javax.swing.JButton BotaoGravarC;
    private javax.swing.JButton BotaoLimparC;
    private javax.swing.JButton BotaoLimparF;
    private javax.swing.JButton BotaoSalvarF;
    private javax.swing.JButton BotaoVoltarC;
    private javax.swing.JButton BotaoVoltarF;
    private javax.swing.JTextField CampoCargoF;
    private javax.swing.JTextField CampoCod;
    private javax.swing.JTextField CampoEndereço;
    private javax.swing.JTextField CampoIdadeF;
    private javax.swing.JTextField CampoMatriculaF;
    private javax.swing.JTextField CampoNomeC;
    private javax.swing.JTextField CampoNomeF;
    private javax.swing.JTextField CampoSalarioF;
    private javax.swing.JTextField CampoSenhaF;
    private javax.swing.JTextField CampoTelefoneC;
    private javax.swing.JTextField CampoTelefoneF;
    private javax.swing.JCheckBox CheckAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
